### ISSUE TITLE
Black screen after a few minutes of gameplay

### ISSUE THREAD

**Issue by Radplayz** [HyperSoop/Simply-Optimized#10]
Edit: i hit enter too early. woops.

After a few minutes of gameplay, the game just freezes. once i take it out of fullscreen and put it back it, it starts freaking out and flashing the mojang logo and a black screen, although i do hear game sounds. I have to force close minecraft for it to be fixed. This never happens with FO.

**Comment by HyperSoop** [comment]
I think this issue has been handled over on Discord
