### ISSUE TITLE
Block breaking issue.

### ISSUE THREAD

**Issue by LarryIsBetter** [HyperSoop/Simply-Optimized#11]
I'm having issues when I hold down the button to break blocks this is happening with mouse and controller.

If I hold down the break button the first block breaks but then next ones don't and keep infinity breaking, if I break the first block let go of the breaking button and break the next everything works. This happens only in survival creative works just fine and I'm pretty sure servers also work just fine. I'm using Fedora Silverblue 38 and Controlify if that matters.

**Comment by HyperSoop** [comment]
If you remove Controlify does the issue stop? If so, please report to them. I'm currently semi-busy so i'll get back to this matter in a bit

**Comment by LarryIsBetter** [comment]
I've tried it doesn't work it doesn't seem to happen on the alpha build of fabulously optimized I've compared the mods and all seems ok so I don't know.

**Comment by LarryIsBetter** [comment]
Can I send a screen capture to your email or something I would here but 10mb limit

**Comment by LarryIsBetter** [comment]
https://wormhole.app/bjrQn#UuAKo38e1c8_hYGz6k6Ajw

**Comment by LarryIsBetter** [comment]
I know it's not registering because the controller vibrates whenever I start breaking a block as for isolating the mod I've tried so I decided to disable all the mods and it was still happening I thought it might have been a 1.20 issue so I loaded up a completely stock instance but it wasn't happening

**Comment by LarryIsBetter** [comment]
yes

**Comment by HyperSoop** [comment]
Then i don't know what might be going wrong,

**Comment by LarryIsBetter** [comment]
I fixed it I completely removed prism from my .var (flatpak) and install the latest 1.20 SO

**Comment by HyperSoop** [comment]
good to hear it's resolved!
