### ISSUE TITLE
[Suggestion] ModMenu

### ISSUE THREAD

**Issue by NoltoxGit** [HyperSoop/Simply-Optimized#12]
Hello,
Thanks for your simplistic optimization modpack !

Can you add the [ModMenu](https://modrinth.com/mod/modmenu) mod please ?
Every time I have to add it manually, but if you can make it the default it would be great :)

Thank you so much,
~ Noltox ~

**Comment by HyperSoop** [comment]
Sorry, no, that's outside the scope of the modpack.
