### ISSUE TITLE
Freezes after Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

### ISSUE THREAD

**Issue by Abelkrijgtalles** [HyperSoop/Simply-Optimized#15]
Simply Optimized freezes after Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

**Comment by HyperSoop** [comment]
This isn't enough context for me to provide help. You should send the game logs in full. (you should also try to isolate the culprit mod, so by taking mods out until the issue no longer appears)

**Comment by Abelkrijgtalles** [comment]
[latest.log](https://github.com/HyperSoop/Simply-Optimized/files/12232790/latest.log)

**Comment by HyperSoop** [comment]
> [latest.log](https://github.com/HyperSoop/Simply-Optimized/files/12232790/latest.log)

Does the issue occur in a fresh instance of SO with no extra mods? If not, try removing your added mods to isolate it to a single specific mod causing a problem. my first suspicion here would be PhysicsMod, as it gives an error earlier in the log about models or something. You could try disabling mixin.perf.dynamic_resources in modernfix-mixins.properties (iirc) and seeing if this helps.

**Comment by Abelkrijgtalles** [comment]
It still freezes with a new installation

**Comment by Abelkrijgtalles** [comment]
Sometimes it works, and sometimes it freezes

**Comment by Abelkrijgtalles** [comment]
It shuffles like every month

**Comment by HyperSoop** [comment]
No idea what might be going on here

**Comment by HyperSoop** [comment]
hmm

**Comment by HyperSoop** [comment]
Oh right

**Comment by HyperSoop** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/899

**Comment by Abelkrijgtalles** [comment]
Thank you, it's fixed now.
