### ISSUE TITLE
[Suggestion] Methane

### ISSUE THREAD

**Issue by seriousfreezing** [HyperSoop/Simply-Optimized#16]
It's much better than Starlight and everything else.

**Comment by HyperSoop** [comment]
No.

**Comment by seriousfreezing** [comment]
Why?

**Comment by HyperSoop** [comment]
Methane majorly sacrifices visuals to impove on performance, and this is not within the goals of SO.

**Comment by seriousfreezing** [comment]
Oh, I didn't know it was at the expense of visual parts. So it would only be good to use this mod for extreme situations of very weak computers, would it?

**Comment by HyperSoop** [comment]
yeah
