### ISSUE TITLE
Experimental sign text buffering is on by default

### ISSUE THREAD

**Issue by khankul** [HyperSoop/Simply-Optimized#17]
This modpack enables ImmediatelyFast's setting `experimental_sign_text_buffering`, which leads to sign rendering issues with Unicode characters - see RalphMC/ImmediatelyFast#117

**Comment by HyperSoop** [comment]
I know, but it's fine to me.

**Comment by khankul** [comment]
Can't recommend this pack to my friends then.

**Comment by HyperSoop** [comment]
If you're negatively affected by the option being enabled, it's easy to switch it off. (I generally encourage modifying the pack locally to better suit your preferences.)
