### ISSUE TITLE
[Suggestion] Noisium

### ISSUE THREAD

**Issue by RealMamitler** [HyperSoop/Simply-Optimized#18]
https://modrinth.com/mod/noisium
It says it has 1:1 parity with Vanilla worldgen, and apparently has good compatibility with other mods (such as sodium).

**Comment by HyperSoop** [comment]
I've been testing this mod and haven't noticed a major difference from vanilla's worldgen speeds. I'm excited to see what it gets updated with in the future though

**Comment by RealMamitler** [comment]
K, thanks for feedback

**Comment by RealMamitler** [comment]
I've done some testing really quickly with and without noisium, and yeah there isn't much of a difference on my high-end computer. Seems to be a 1-2 second speedup

**Comment by RealMamitler** [comment]
I'm wondering maybe on very low-end computers this mod could help? But I can't really test that so \_(-_-)_/

**Comment by digbick000** [comment]
The sentence has minor syntactical and spelling errors. An improved version could be:
I've tried Nosium on my "low-end laptop, and it gave me an increase in **performance** in chunk loading. Before, I would have an average of 160 fps, but with Nosium, it increased to an average of 200 fps.

Here are the specs: Intel Core i5 7200u and a dedicated GPU, the Nvidia Geforce MX130."

**Comment by digbick000** [comment]
I've tried Nosium on my "low-end laptop, and it gave me an increase in performance in chunk loading. Before, I would have an average of 160 fps, but with Nosium, it increased to an average of 200 fps.

Here are the specs: Intel Core i5 7200u and a dedicated GPU, the Nvidia Geforce MX130."

**Comment by RealMamitler** [comment]
Hmm. Intresting, I should probably also test fps as well. Mind me asking how did you test fps? Were you flying around or?

**Comment by HyperSoop** [comment]
> I've tried Nosium on my "low-end laptop, and it gave me an increase in **performance** in chunk loading. Before, I would have an average of 160 fps, but with Nosium, it **increased** to an average of 200 fps. Edit: I would recommend this mod.
> 
> Here are the specs: Intel Core i5 7200u and a dedicated GPU, the Nvidia Geforce MX130."

Jokes on you my machine is lower-end than that :)
Anyway, just making sure, did you test this within SO or in another modpack or by itself?

**Comment by HyperSoop** [comment]
I tested the mod again and on my setup it doesn't seem to have much of a performance impact. It seems to be a bit better with the mod, but not enough so to be able to claim it's not test variance.

**Comment by RealMamitler** [comment]
Hmm. Should I close this issue then until Noisium gets a huge upgrade or something similar that gains a huge peformance boost when generating world terrain, or?

**Comment by HyperSoop** [comment]
The mod is now in SO anyway. I've decided to give it a shot lol
