### ISSUE TITLE
[Suggestion] Starlight

### ISSUE THREAD

**Issue by digbick000** [HyperSoop/Simply-Optimized#19]
in your mod you have Concurrent Chunk Management Engine 
and with starlight i think it would be a great combo together

**Comment by RealMamitler** [comment]
Quote from starlight: "Please see: https://gist.github.com/Spottedleaf/6cc1acdd03a9b7ac34699bf5e8f1b85c TL;DR Mojang improved upon their own light engine using the same performance critical designs from Starlight. As a result, they have closed the performance gap, obsoleting Starlight on the client side."
You mean add starlight in newer versions? (1.20 and above)

**Comment by digbick000** [comment]
yes 1.20 and above ;)

**Comment by digbick000** [comment]
Oh yeah you are right thanks. 👍
