### ISSUE TITLE
Remove "More Culling" by fxmorin

### ISSUE THREAD

**Issue by TheDcoder** [HyperSoop/Simply-Optimized#23]
He is not a trustworthy developer: https://www.youtube.com/watch?v=hxIzMQUlDLI

I wasn't aware of it until someone shared this video with me on IRC. I personally removed it from my instance and in my opinion it should be removed from the mod pack as well since the author is known to spread malicious code.

**Comment by HyperSoop** [comment]
that's extremely old news. i think i've briefly heard of that drama; i'm certain fx isn't the same person today as he was 2 years ago, is very sorry about what he's done there and won't do it again.

**Comment by TheDcoder** [comment]
Do we know how much the culling mod contributes to performance? If it isn't significant then it significantly outweighs the potential risks.

**Comment by HyperSoop** [comment]
not really atm. i could benchmark the game with and without the mod but i don't think that's nessesary, once again, the video you've sent is extremely old news and i trust fx to have become a better person since then.
