### ISSUE TITLE
Remove the Nvidium from the wiki

### ISSUE THREAD

**Issue by seriousfreezing** [HyperSoop/Simply-Optimized#25]

**Comment by SirenityK** [comment]
I was wondering why nvidium has been removed, did you had any issues or it was too experimental to keep it in the wiki?

**Comment by HyperSoop** [comment]
> I was wondering why nvidium has been removed, did you had any issues or it was too experimental to keep it in the wiki?

1. it was added to SO itself at some point
2. it's no longer in it now due to being unmaintained
