### ISSUE TITLE
Crosshair issue

### ISSUE THREAD

**Issue by 1AboDa7m** [HyperSoop/Simply-Optimized#26]
my crosshair not showing i uninstall it and reinstall and didn't work

**Comment by HyperSoop** [comment]
what other mods are you using? this could probably be remedied by setting `"experimental_universal_hud_batching"` to false in `config/immediatelyfast.json`

**Comment by MrTronMan** [comment]
> what other mods are you using? this could probably be remedied by setting `"experimental_universal_hud_batching"` to false in `config/immediatelyfast.json`

Hi, my friend had similar issues and the modpack was default, no other mods besides the ones that came pre installed. But this did the trick, thank you!
