### ISSUE TITLE
Linked Minecraft Performance Flags Out of Date

### ISSUE THREAD

**Issue by JamieBra** [HyperSoop/Simply-Optimized#27]
Due to the currently linked GitHub repo for Minecraft performance flags being out of date for Java 21, can I suggest linking a more up-to-date fork: https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks

**Comment by HyperSoop** [comment]
I know about that fork but i'm not sure they've really changed much? 90% of it is the same as the original guide

**Comment by JamieBra** [comment]
It's similar but a big change is that the downloads have been updated to include information about Java 21. I found acquiring the correct version of GraalVM to be pretty confusing with the original guide since Enterprise Edition isn't a thing anymore. Also, I believe some of the flags have been updated for the newer versions. I couldn't say how much of a difference it makes for performance, however.

**Comment by HyperSoop** [comment]
yeah it's still a good call to update the link.

**Comment by HyperSoop** [comment]
done
