### ISSUE TITLE
Spelling error in Wiki's FAQ page

### ISSUE THREAD

**Issue by LastPuppet** [HyperSoop/Simply-Optimized#28]
specifically, in line "It must be an optimization (-focused) mod. Only mods to optimize rendering, server code or in some way make the base game more efficent are considered. No visual enhancements or QoL utilities. Mods that add options to cut down on visual quality for perfromance (Sodium Extra, for example) are also not being considered."

"efficent" should be replaced with efficient
and "perfromance" should be replaced with performance

Cheers

**Comment by HyperSoop** [comment]
thanks

**Comment by HyperSoop** [comment]
fixed
