### ISSUE TITLE
1.21.1 modpack release can be updated

### ISSUE THREAD

**Issue by LastPuppet** [HyperSoop/Simply-Optimized#29]
Fabric API and ImmediatelyFast have all updated to 1.21.1

Fabric API: https://modrinth.com/mod/fabric-api/version/0.102.0+1.21.1
ImmediatelyFast: https://modrinth.com/mod/immediatelyfast/version/1.2.19+1.21.1-fabric

Cheers,
Real

**Comment by HyperSoop** [comment]
this doesn't need a whole github issue lol

**Comment by LastPuppet** [comment]
oops i guess
