### ISSUE TITLE
Set default simulation distance to 8 chunks to avoid mob farms breaking.

### ISSUE THREAD

**Issue by notadev01** [HyperSoop/Simply-Optimized#32]
[This Reddit post](https://old.reddit.com/r/technicalminecraft/comments/1fqc9dm/does_simulation_distance_affect_the_128blocks_mob/) and the link to the wiki within explains it better, but simply put, the mob spawning mechanics work like this: 

<details><summary>Mob spawning radius</summary>

![Mob spawning radius](https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4a/Mob_spawning_ranges.png/revision/latest?cb=20190504035227)
</details>

However, if you lower the simulation distance from 8 chunks (and thus, lower from 128 blocks), this will leave mobs unloaded which makes them unable to despawn, but still contributing to the mob cap. This could mess up mob farms, and unless someone does their research they wouldn't know how to fix it, so I think it's best if it's set to 8 by default.

**Comment by HyperSoop** [comment]
Perfect vanilla parity is not the goal of this modpack though, and since noone's brought this up with me before i think it's best if you just adjust the simulation distance to 8 by yourself upon installing it
