### ISSUE TITLE
Sign Text sometimes not showing

### ISSUE THREAD

**Issue by SamuelBorn** [HyperSoop/Simply-Optimized#33]
Text of normal signs is not loaded sometimes.

I am using SO **1.21.1-4.0.1** on Fedora Linux with NVIDIA Drivers 560.35.03.

A quick relog fixes this issue.

I could not find a pattern when in brakes.
Sorry for the vague bug report! Just wanted to let you know.

**Comment by HyperSoop** [comment]
try disabling `experimental_sign_text_buffering` in `/config/immediatelyfast.json`

**Comment by SamuelBorn** [comment]
Yep, this fixed it. Thank you!
