### ISSUE TITLE
FastAnim

### ISSUE THREAD

**Issue by Baxtroy** [HyperSoop/Simply-Optimized#5]
FastAnim is a mod which increases animation perfomance by using variables
Link:
https://modrinth.com/mod/fastanim

**Comment by HyperSoop** [comment]
It was tested to not give a positive perfomance impact, however i'm keeping this open for further tests and discussion

**Comment by qb20nh** [comment]
> making PI/180 a stored value that isn't calculated multiple times

I'm pretty sure java compiler inlines all constant expressions

> using variables instead of repeated calculations

Isn't this just the opposite of the first one?

I'm not sure the author of this mod is knowledgeable enough in what the mod is effectively doing.

**Comment by qb20nh** [comment]
> making PI/180 a stored value that isn't calculated multiple times

I'm pretty sure that the java compiler inlines all constant expressions

> using variables instead of repeated calculations

Isn't this just the opposite of the above?

**Comment by HyperSoop** [comment]
can always reopen later
