### ISSUE TITLE
Performance comparisons to vanilla and other packs

### ISSUE THREAD

**Issue by Baxtroy** [HyperSoop/Simply-Optimized#6]
Your modpack is awesome. But, we need proof of what you claim. See Light Craft for example. It shows proof of what it claims. I recommend you add comparison with other fps packs and vanilla

**Comment by HyperSoop** [comment]
though anyone could just try it and see, yeah, that'd be a nice addition to the description. i'll do it sodium-style

**Comment by HyperSoop** [comment]
done @Baxtroy check it out on the project page
