### ISSUE TITLE
ReShade

### ISSUE THREAD

**Issue by Icy687** [HyperSoop/Simply-Optimized#7]
Not related to modpack however it's mentioned in the wiki so I might just ask here:
I loaded up and activated your ReShade preset and nothing happened, am I missing the shaders/textures etc that are required for the preset to run?
ReShade is working as expected as I installed and used some random shaders just to check if the installation went right.

**Comment by HyperSoop** [comment]
It should download the shader required if you've used it right on installation, it uses MagicHDR by luluco250 https://github.com/luluco250/FXShaders/blob/master/Shaders/MagicHDR.fx

if you need any further help just ask

**Comment by Icy687** [comment]
During installation of ReShade, it doesn't give me any options to choose what shaders or effects I want to include, it just says "installed" once I go through the first few steps. I am not sure but I think this is a known issue.

In short, once i put MagicHDR.fx in my shaders directory and click your preset, it should run properly?

**Comment by HyperSoop** [comment]
> During installation of ReShade, it doesn't give me any options to choose what shaders or effects I want to include, it just says "installed" once I go through the first few steps. I am not sure but I think this is a known issue.
> 
> In short, once i put MagicHDR.fx in my shaders directory and click your preset, it should run properly?

I've never encountered such issues myself. I think yeah you should try that

**Comment by Icy687** [comment]
I am double clicking your preset in the in-game overlay but it does not activate MagicHDR automatically, I could just enable it manually but obviously I don't understand how I will be able to apply the configurations in your preset for that shader.

**Comment by HyperSoop** [comment]
does it work now?

**Comment by Icy687** [comment]
I mean, applying the preset is still not doing anything, I was about to apply all the configurations manually myself.

**Comment by HyperSoop** [comment]
You can always re-enable it later.

**Comment by Icy687** [comment]
Okay then, thanks for the help.
