### ISSUE TITLE
Let Me Despawn

### ISSUE THREAD

**Issue by qb20nh** [HyperSoop/Simply-Optimized#8]
https://modrinth.com/plugin/lmd

>Improves performance by tweaking mob despawn rules.
>
>...
>LMD tweaks the despawn check to allow mobs that pick up or equip items from the ground to naturally despawn like any other mob.

- Does not improve the game's intrinsic performance
- Direct and significant game mechanic change

**Comment by HyperSoop** [comment]
wait why are you even suggesting it if you already know it doesn't fit
